# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-26 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='album',
            name='genr',
            field=models.CharField(max_length=350),
        ),
    ]
